/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 coffeeSteamModel.glb -t
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import CoffeeShaderMaterial from '../shaders/coffeeSteam'

type GLTFResult = GLTF & {
  nodes: {
    Plane013: THREE.Mesh
  }
  materials: {}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/roomIn3d/coffeeSteamModel.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane013.geometry} position={[-1.4, 2.66, -3.42]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <CoffeeShaderMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/roomIn3d/coffeeSteamModel.glb')
