/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 elgatoLightModel.glb -t
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane034: THREE.Mesh
  }
  materials: {}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/roomIn3d/elgatoLightModel.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane034.geometry} position={[-0.06, 4.59, -4.56]} rotation={[1.82, -0.09, -0.34]} scale={1.1}>
        <meshBasicMaterial color="#ffffff" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/roomIn3d/elgatoLightModel.glb')
