/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 loupedeckButtonsModel.glb -t
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    screen001: THREE.Mesh
    screen004: THREE.Mesh
    screen003: THREE.Mesh
    screen002: THREE.Mesh
    screen007: THREE.Mesh
    screen006: THREE.Mesh
    screen005: THREE.Mesh
    screen010: THREE.Mesh
    screen009: THREE.Mesh
    screen008: THREE.Mesh
    screen013: THREE.Mesh
    screen012: THREE.Mesh
    screen011: THREE.Mesh
    screen014: THREE.Mesh
  }
  materials: {}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/roomIn3d/loupedeckButtonsModel.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.screen001.geometry} material={nodes.screen001.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen004.geometry} material={nodes.screen004.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen003.geometry} material={nodes.screen003.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen002.geometry} material={nodes.screen002.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen007.geometry} material={nodes.screen007.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen006.geometry} material={nodes.screen006.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen005.geometry} material={nodes.screen005.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen010.geometry} material={nodes.screen010.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen009.geometry} material={nodes.screen009.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen008.geometry} material={nodes.screen008.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen013.geometry} material={nodes.screen013.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen012.geometry} material={nodes.screen012.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen011.geometry} material={nodes.screen011.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
      <mesh geometry={nodes.screen014.geometry} material={nodes.screen014.material} position={[0.15, 2.46, -4.35]} rotation={[0.29, 0, 0]} scale={[0.17, 0.12, 0.1]}>
        <meshBasicMaterial color="#ffffff" transparent={true} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/roomIn3d/loupedeckButtonsModel.glb')
