/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 pcScreenModel.glb -t
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube271: THREE.Mesh
  }
  materials: {}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/roomIn3d/pcScreenModel.glb') as GLTFResult
  const texture = useVideoTexture("/roomIn3d/videoPortfolio.mp4")
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube271.geometry} position={[0.31, 3.36, -4.59]} rotation={[0, 1.57, -1.57]}>
        <meshBasicMaterial map={texture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/roomIn3d/pcScreenModel.glb')
