/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 topChairModel.glb -t
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import BakedShaderMaterial from '../shaders/baked'

type GLTFResult = GLTF & {
  nodes: {
    Cube318: THREE.Mesh
  }
  materials: {}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/roomIn3d/topChairModel.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.81, 1.3, -1.53]}>
        <mesh geometry={nodes.Cube318.geometry} material={nodes.Cube318.material} position={[-0.68, 0.12, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <BakedShaderMaterial />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/roomIn3d/topChairModel.glb')
